### ISSUE TITLE
Version 0.12.0-da3e197 - Fails to start after latest update. Logs don't show where the errors are in the config

### ISSUE THREAD

**Issue by Gahrlaag** [blakeblackshear/frigate-hass-addons#109]
So after the latest update, I get a log error , stating that the config file is incorrect in frigate but I'm unable to see what's wrong with the config? 

**The LOG:** 

s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
2023-04-12 18:18:32.996707479  [INFO] Preparing go2rtc config...
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2023-04-12 18:18:33.002896656  [INFO] Starting Frigate...
2023-04-12 18:18:33.004152248  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
2023-04-12 18:18:33.042695199  [INFO] Got IP address from supervisor: 192.168.88.48
2023-04-12 18:18:33.077346382  [INFO] Got WebRTC port from supervisor: 8555
2023-04-12 18:18:33.303654617  [INFO] Starting go2rtc...
2023-04-12 18:18:33.372296605  20:18:33.372 INF go2rtc version 1.2.0 linux/amd64
2023-04-12 18:18:33.372758411  20:18:33.372 INF [api] listen addr=:1984
2023-04-12 18:18:33.373058295  20:18:33.373 INF [rtsp] listen addr=:8554
2023-04-12 18:18:33.373352813  20:18:33.373 INF [srtp] listen addr=:8443
2023-04-12 18:18:33.373617264  20:18:33.373 INF [webrtc] listen addr=:8555
2023-04-12 18:18:34.215780817  [2023-04-12 20:18:34] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
2023-04-12 18:18:34.225750258  *************************************************************
2023-04-12 18:18:34.225753254  *************************************************************
2023-04-12 18:18:34.225756999  ***    Your config file is not valid!                     ***
2023-04-12 18:18:34.225759168  ***    Please check the docs at                           ***
2023-04-12 18:18:34.225760636  ***    https://docs.frigate.video/configuration/index     ***
2023-04-12 18:18:34.225773408  *************************************************************
2023-04-12 18:18:34.225774836  *************************************************************
2023-04-12 18:18:34.225776535  ***    Config Validation Errors                           ***
2023-04-12 18:18:34.225777854  *************************************************************
2023-04-12 18:18:34.225779134  Config input objects is defined multiple times for the same field, this is not allowed.
2023-04-12 18:18:34.227309919  Traceback (most recent call last):
2023-04-12 18:18:34.227312450    File "/opt/frigate/frigate/app.py", line 351, in start
2023-04-12 18:18:34.227313764      self.init_config()
2023-04-12 18:18:34.227315105    File "/opt/frigate/frigate/app.py", line 80, in init_config
2023-04-12 18:18:34.227316389      user_config = FrigateConfig.parse_file(config_file)
2023-04-12 18:18:34.227317715    File "/opt/frigate/frigate/config.py", line 1068, in parse_file
2023-04-12 18:18:34.227318904      config = load_config_with_no_duplicates(raw_config)
2023-04-12 18:18:34.227320156    File "/opt/frigate/frigate/util.py", line 78, in load_config_with_no_duplicates
2023-04-12 18:18:34.227321315      return yaml.load(raw_config, PreserveDuplicatesLoader)
2023-04-12 18:18:34.227322601    File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 81, in load
2023-04-12 18:18:34.227323691      return loader.get_single_data()
2023-04-12 18:18:34.227325037    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 51, in get_single_data
2023-04-12 18:18:34.227326694      return self.construct_document(node)
2023-04-12 18:18:34.227328065    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 55, in construct_document
2023-04-12 18:18:34.227359674      data = self.construct_object(node)
2023-04-12 18:18:34.227361211    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 100, in construct_object
2023-04-12 18:18:34.227362510      data = constructor(self, node)
2023-04-12 18:18:34.227363745    File "/opt/frigate/frigate/util.py", line 63, in map_constructor
2023-04-12 18:18:34.227365022      vals = [loader.construct_object(node, deep=deep) for _, node in node.value]
2023-04-12 18:18:34.227366593    File "/opt/frigate/frigate/util.py", line 63, in <listcomp>
2023-04-12 18:18:34.227367924      vals = [loader.construct_object(node, deep=deep) for _, node in node.value]
2023-04-12 18:18:34.227369335    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 100, in construct_object
2023-04-12 18:18:34.227380392      data = constructor(self, node)
2023-04-12 18:18:34.227381701    File "/opt/frigate/frigate/util.py", line 63, in map_constructor
2023-04-12 18:18:34.227383013      vals = [loader.construct_object(node, deep=deep) for _, node in node.value]
2023-04-12 18:18:34.227384790    File "/opt/frigate/frigate/util.py", line 63, in <listcomp>
2023-04-12 18:18:34.227386126      vals = [loader.construct_object(node, deep=deep) for _, node in node.value]
2023-04-12 18:18:34.227387501    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 100, in construct_object
2023-04-12 18:18:34.227399622      data = constructor(self, node)
2023-04-12 18:18:34.227400926    File "/opt/frigate/frigate/util.py", line 68, in map_constructor
2023-04-12 18:18:34.227402008      raise ValueError(
2023-04-12 18:18:34.227403397  ValueError: Config input objects is defined multiple times for the same field, this is not allowed.
2023-04-12 18:18:34.227404561  
2023-04-12 18:18:34.227405834  *************************************************************
2023-04-12 18:18:34.227407024  ***    End Config Validation Errors                       ***
2023-04-12 18:18:34.227408258  *************************************************************
2023-04-12 18:18:35.363943671  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-04-12 18:18:35.375284824  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-04-12 18:18:35.396339931  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
2023-04-12 18:18:35.400604669  exit OK
s6-rc: info: service frigate-log successfully stopped
2023-04-12 18:18:35.404822134  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**The config file** 

mqtt:
  host: 192.168.88.17

cameras:
  huvudingangen:
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxxxxxxx@192.168.88.39:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - record
            - detect
    detect: 
      width: 1920
      height: 1080
      fps: 10
    record:
      enabled: true
      retain_days: 0
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 5
    objects: 
      track:
        - person
        - cat
        - bird
      filters:
        person:
          min_area: 5000
          max_area: 90000
          min_ratio: 0.5
          max_ratio: 2.0
          min_score: 0.8
          threshold: 0.7
    snapshots:
      enabled: true
      timestamp: true
      crop: False
      retain:
        default: 5
    motion:
      mask:
        - 0,0,713,0,770,0,1683,0,1920,0,1806,181,1462,115,1160,35,1032,23,946,74,956,146,913,201,828,237,765,259,697,281,672,314,636,334,590,429,571,440,539,474,493,481,468,501,422,594,357,606,230,1080,0,1080
  uppfarten:
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxxxxx@192.168.88.34:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - record
            - detect
    detect: 
      width: 1920
      height: 1080
      fps: 10
    record:
      enabled: true
      retain_days: 0
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 5
    objects: 
      track:
        - person
        - cat
        - bird
      filters:
        person:
          min_area: 5000
          max_area: 90000
          min_ratio: 0.5
          max_ratio: 2.0
          min_score: 0.8
          threshold: 0.7
    objects: 
      track:
        - person
    snapshots:
      enabled: True
      timestamp: True
      crop: False
      retain:
        default: 5
    motion:
      mask:
        - 0,0,244,0,603,0,606,83,510,102,513,125,227,199,204,1080,0,1080
        - 645,0,640,55,606,55,605,0
        - 1209,0,1203,84,1113,75,1118,0
        - 1545,0,1531,125,1470,122,1486,0
        - 1898,0,1854,291,1553,173,1569,0
        - 1404,0,1387,90,1313,75,1320,0
rtmp:
  enabled: false
detectors:
  coral:
    type: edgetpu
    device: usb

**Comment by NickM-27** [comment]
since your code has no formatting it is difficult to see, but somewhere you have a duplicate field under the same camera which is not allowed in 0.12

**Comment by Gahrlaag** [comment]
Ah, I had a duplicate  objects:
