### ISSUE TITLE
Detection not working after latest update

### ISSUE THREAD

**Issue by Gahrlaag** [blakeblackshear/frigate-hass-addons#110]
After the config issue that I managed to resolve, I noticed that I'm no longer getting any detections at all?
Opening the frigate logs, shows these errors. 

2023-04-12 19:03:30.607507010  [INFO] Starting Frigate...
2023-04-12 19:03:32.252371368  [2023-04-12 21:03:32] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
2023-04-12 19:03:32.272056456  [2023-04-12 21:03:32] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'
2023-04-12 19:03:32.276555914  [2023-04-12 21:03:32] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'
2023-04-12 19:03:32.289030965  [2023-04-12 21:03:32] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-04-12 19:03:32.289915490  [2023-04-12 21:03:32] peewee_migrate                 INFO    : Starting migrations
2023-04-12 19:03:32.296297122  [2023-04-12 21:03:32] peewee_migrate                 INFO    : There is nothing to migrate
2023-04-12 19:03:32.315430300  [2023-04-12 21:03:32] frigate.app                    INFO    : Output process started: 301
2023-04-12 19:03:32.329998673  [2023-04-12 21:03:32] frigate.app                    INFO    : Camera processor started for huvudingangen: 308
2023-04-12 19:03:32.337014085  [2023-04-12 21:03:32] frigate.app                    INFO    : Camera processor started for uppfarten: 310
2023-04-12 19:03:32.352032903  [2023-04-12 21:03:32] frigate.app                    INFO    : Capture process started for huvudingangen: 313
2023-04-12 19:03:32.352036786  [2023-04-12 21:03:32] frigate.app                    INFO    : Capture process started for uppfarten: 314
2023-04-12 19:03:34.941456505  [2023-04-12 21:03:32] detector.coral                 INFO    : Starting detection process: 300
2023-04-12 19:03:34.941607045  [2023-04-12 21:03:32] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-04-12 19:03:34.959074050  [2023-04-12 21:03:34] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-04-12 19:14:50.772990026  [2023-04-12 21:14:50] frigate.http                   ERROR   : Exception on /huvudingangen/latest.jpg [GET]
2023-04-12 19:14:50.772993227  Traceback (most recent call last):
2023-04-12 19:14:50.772994778    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2528, in wsgi_app
2023-04-12 19:14:50.772997145      response = self.full_dispatch_request()
2023-04-12 19:14:50.772998768    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1825, in full_dispatch_request
2023-04-12 19:14:50.773012743      rv = self.handle_user_exception(e)
2023-04-12 19:14:50.773014283    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1823, in full_dispatch_request
2023-04-12 19:14:50.773016014      rv = self.dispatch_request()
2023-04-12 19:14:50.773017421    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1799, in dispatch_request
2023-04-12 19:14:50.773031651      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-12 19:14:50.773033047    File "/opt/frigate/frigate/http.py", line 896, in latest_frame
2023-04-12 19:14:50.773034542      frame = cv2.resize(frame, dsize=(width, height), interpolation=cv2.INTER_AREA)
2023-04-12 19:14:50.773036111  cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/resize.cpp:4055: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'
2023-04-12 19:14:50.773045882  
2023-04-12 19:14:50.773047423  [2023-04-12 21:14:50] frigate.http                   ERROR   : Exception on /uppfarten/latest.jpg [GET]
2023-04-12 19:14:50.773048577  Traceback (most recent call last):
2023-04-12 19:14:50.773050032    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2528, in wsgi_app
2023-04-12 19:14:50.773051278      response = self.full_dispatch_request()
2023-04-12 19:14:50.773052683    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1825, in full_dispatch_request
2023-04-12 19:14:50.773063308      rv = self.handle_user_exception(e)
2023-04-12 19:14:50.773064760    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1823, in full_dispatch_request
2023-04-12 19:14:50.773065870      rv = self.dispatch_request()
2023-04-12 19:14:50.773067312    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1799, in dispatch_request
2023-04-12 19:14:50.773068626      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-12 19:14:50.773069861    File "/opt/frigate/frigate/http.py", line 896, in latest_frame
2023-04-12 19:14:50.773082473      frame = cv2.resize(frame, dsize=(width, height), interpolation=cv2.INTER_AREA)
2023-04-12 19:14:50.773084085  cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/resize.cpp:4055: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'
2023-04-12 19:14:50.773085102  
2023-04-12 19:47:08.742220539  [2023-04-12 21:47:08] frigate.http                   ERROR   : Exception on /uppfarten/latest.jpg [GET]
2023-04-12 19:47:08.742226323  Traceback (most recent call last):
2023-04-12 19:47:08.742227871    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2528, in wsgi_app
2023-04-12 19:47:08.742229204      response = self.full_dispatch_request()
2023-04-12 19:47:08.742230672    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1825, in full_dispatch_request
2023-04-12 19:47:08.742231847      rv = self.handle_user_exception(e)
2023-04-12 19:47:08.742233201    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1823, in full_dispatch_request
2023-04-12 19:47:08.742234307      rv = self.dispatch_request()
2023-04-12 19:47:08.742235642    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1799, in dispatch_request
2023-04-12 19:47:08.742236945      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-12 19:47:08.742238198    File "/opt/frigate/frigate/http.py", line 896, in latest_frame
2023-04-12 19:47:08.742239485      frame = cv2.resize(frame, dsize=(width, height), interpolation=cv2.INTER_AREA)
2023-04-12 19:47:08.742241018  cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/resize.cpp:4055: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'
2023-04-12 19:47:08.742242082  
2023-04-12 19:47:08.743931264  [2023-04-12 21:47:08] frigate.http                   ERROR   : Exception on /huvudingangen/latest.jpg [GET]
2023-04-12 19:47:08.743934948  Traceback (most recent call last):
2023-04-12 19:47:08.743936549    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2528, in wsgi_app
2023-04-12 19:47:08.743937944      response = self.full_dispatch_request()
2023-04-12 19:47:08.743939449    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1825, in full_dispatch_request
2023-04-12 19:47:08.743940639      rv = self.handle_user_exception(e)
2023-04-12 19:47:08.743942039    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1823, in full_dispatch_request
2023-04-12 19:47:08.743943220      rv = self.dispatch_request()
2023-04-12 19:47:08.743944568    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1799, in dispatch_request
2023-04-12 19:47:08.743945842      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-12 19:47:08.743947063    File "/opt/frigate/frigate/http.py", line 896, in latest_frame
2023-04-12 19:47:08.743948282      frame = cv2.resize(frame, dsize=(width, height), interpolation=cv2.INTER_AREA)
2023-04-12 19:47:08.743949831  cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/resize.cpp:4055: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'
2023-04-12 19:47:08.743950899

**Comment by NickM-27** [comment]
those are frontend errors unrelated to detection. Are you sure that detect is enabled in the frontend?

**Comment by Gahrlaag** [comment]
![5394c11f02e46566bdad7397d0fedacb](https://user-images.githubusercontent.com/58030953/231570439-90f201ea-410b-41a1-a440-b26e6a419f06.png)

Unless something's changed, yes

**Comment by NickM-27** [comment]
and if you watch the debug live view with bounding boxes on, nothing is getting detected?

**Comment by Gahrlaag** [comment]
Nope, nothing. Just went to check.

**Comment by Gahrlaag** [comment]
here's the config - https://pastebin.com/ctBGTGdU

**Comment by Gahrlaag** [comment]
So I restarted everything yesterday and removed the following from the config 

          min_area: 5000
          max_area: 90000
          min_ratio: 0.5
          max_ratio: 2.0

And everything just started working out of the blue..?
