### ISSUE TITLE
CORAL TPU M.2 B+M MODULE not find frigate /HAOS on NUC type

### ISSUE THREAD

**Issue by seblang** [blakeblackshear/frigate-hass-addons#164]
I have installed a CORAL TPU M.2 B+M MODULE ([212-G650-04686-01]) M2 slot of my NUC (HAOS).
I have added in the config but frigate do not find it

**frigate.yml**

detectors:
  coral:
    type: edgetpu
    device: pci

**Logs:**

2024-03-29 16:52:57.772646385  [2024-03-29 17:52:57] detector.coral                 INFO    : Starting detection process: 316
2024-03-29 16:52:57.776582483  [2024-03-29 17:52:57] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci:0
2024-03-29 16:52:57.778798354  [2024-03-29 17:52:57] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2024-03-29 16:52:57.778803989  [2024-03-29 17:52:57] frigate.app                    INFO    : Output process started: 318
2024-03-29 16:52:57.778805736  Process detector:coral:
2024-03-29 16:52:57.778806857  Traceback (most recent call last):
2024-03-29 16:52:57.778808706    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
2024-03-29 16:52:57.778809771      delegate = Delegate(library, options)
2024-03-29 16:52:57.778810978    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
2024-03-29 16:52:57.778920252      raise ValueError(capture.message)
2024-03-29 16:52:57.778938134  ValueError
2024-03-29 16:52:57.778960475  
2024-03-29 16:52:57.778989546  During handling of the above exception, another exception occurred:
2024-03-29 16:52:57.779095198

**Comment by Jbvest88** [comment]
same i cant get my a+e key dual edge TPU to work, tried different ways of working the dectors that ive found and doesnt work, it just doesnt see it. anyone out there please help us!
