### ISSUE TITLE
Unable to install in HassOS

### ISSUE THREAD

**Issue by stjones-dev** [blakeblackshear/frigate-hass-addons#18]
Hi,

I have tried and tried but cant get this installed: I created the frigate.yml config file in the root of config directory.

When I try to install I get the following error:

21-03-04 17:35:35 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 'NoneType' object has no attribute 'is_file'
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 100, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 182, in install
    await addon.instance.install(store.version, store.image)
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 32, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 491, in _install
    self._build(version)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 500, in _build
    build_env = AddonBuild(self.coresys, self.addon)
  File "/usr/src/supervisor/supervisor/addons/build.py", line 32, in __init__
    super().__init__(
  File "/usr/src/supervisor/supervisor/utils/common.py", line 59, in __init__
    self.read_data()
  File "/usr/src/supervisor/supervisor/utils/common.py", line 72, in read_data
    if self._file.is_file():
AttributeError: 'NoneType' object has no attribute 'is_file'

Any idea why?

**Comment by sebasvv** [comment]
Seems like a bug [https://community.home-assistant.io/t/supervisor-2021-3-0-local-add-ons-nonetype-object-has-no-attribute-is-file/286350/3](https://community.home-assistant.io/t/supervisor-2021-3-0-local-add-ons-nonetype-object-has-no-attribute-is-file/286350/3)

**Comment by stjones-dev** [comment]
After some time and a few restarts it had finally installed somehow. It didnt work though. All camera images corrupted and server load shot upto 15 or so. Sadly it crashed my system so i've uninstalled and now have to try and fix it as it keeps stopping. I have backups if needed but had made some nice tweaks not yet backed up.

**Comment by sebasvv** [comment]
Issue has been fixed for me in supervisor 2021.03.4
