### ISSUE TITLE
Frigate add-on cannot be started.


### ISSUE THREAD

**Issue by Starcon79** [blakeblackshear/frigate-hass-addons#190]
Since the update to 0.14, the Frigate add-on can no longer be started. I can't make much sense of the log, so maybe someone can help me.

`s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service certsync-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service certsync-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service go2rtc-healthcheck successfully started
2024-11-11 07:08:52.237426159  [INFO] Preparing Frigate...
2024-11-11 07:08:52.238564895  [INFO] Starting NGINX...
2024-11-11 07:08:52.244710442  [INFO] Preparing new go2rtc config...
2024-11-11 07:08:52.248742499  [INFO] No TLS certificate found. Generating a self signed certificate...
2024-11-11 07:08:52.251246353  [INFO] Starting Frigate...
curl: (22) The requested URL returned error: 403 Forbidden
2024-11-11 07:08:52.304218238  [WARN] Failed to get IP address from supervisor
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 136, in <module>
    go2rtc_config["streams"][name][i] = stream.format(**FRIGATE_ENV_VARS)
AttributeError: 'dict' object has no attribute 'format'
2024-11-11 07:08:52.863811145  [INFO] The go2rtc service exited with code 1 (by signal 0)
s6-rc: info: service nginx successfully started
s6-rc: info: service certsync: starting
s6-rc: info: service certsync successfully started
s6-rc: info: service legacy-services: starting
2024-11-11 07:08:53.592419749  [INFO] Starting certsync...
s6-rc: info: service legacy-services successfully started
2024-11-11 07:08:53.690686753  127.0.0.1 - - [11/Nov/2024:08:08:53 +0100] "" 400 0 "-" "-" "-"
2024-11-11 07:08:53.873064497  [INFO] Preparing new go2rtc config...
curl: (22) The requested URL returned error: 403 Forbidden
2024-11-11 07:08:53.928360742  [WARN] Failed to get IP address from supervisor
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 136, in <module>
    go2rtc_config["streams"][name][i] = stream.format(**FRIGATE_ENV_VARS)
AttributeError: 'dict' object has no attribute 'format'
2024-11-11 07:08:54.340899800  [INFO] The go2rtc service exited with code 1 (by signal 0)
2024-11-11 07:08:54.480997721  [2024-11-11 08:08:54] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
2024-11-11 07:08:54.481165880  [2024-11-11 08:08:54] frigate.app                    INFO    : Creating directory: /tmp/cache
2024-11-11 07:08:54.481311308  [2024-11-11 08:08:54] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-11-11 07:08:54.494404919  [2024-11-11 08:08:54] frigate.util.config            INFO    : frigate config does not need migration...
2024-11-11 07:08:54.506469108  [2024-11-11 08:08:54] frigate.util.services          WARNING : Did not detect hwaccel, using a GPU for accelerated video decoding is highly recommended
2024-11-11 07:08:54.508726449  [tcp @ 0x395afac0] Connection to tcp://127.0.0.1:8554?timeout=0 failed: Connection refused
2024-11-11 07:08:54.537132019  [2024-11-11 08:08:54] frigate.app                    INFO    : Making backup of DB before migrations...
2024-11-11 07:08:54.876676669  [2024-11-11 08:08:54] peewee_migrate.logs            INFO    : Starting migrations
2024-11-11 07:08:54.920127795  [2024-11-11 08:08:54] peewee_migrate.logs            INFO    : Migrate "021_create_previews_table"
2024-11-11 07:08:54.920273482  [2024-11-11 08:08:54] peewee_migrate.logs            INFO    : sql ('CREATE TABLE IF NOT EXISTS "previews" ("id" VARCHAR(30) NOT NULL PRIMARY KEY, "camera" VARCHAR(20) NOT NULL, "path" VARCHAR(255) NOT NULL, "start_time" DATETIME NOT NULL, "end_time" DATETIME NOT NULL, "duration" REAL NOT NULL)',)
2024-11-11 07:08:54.922279000  database disk image is malformed
2024-11-11 07:08:54.922542247  [2024-11-11 08:08:54] peewee_migrate.logs            ERROR   : Migration failed: 021_create_previews_table
2024-11-11 07:08:54.922546466  Traceback (most recent call last):
2024-11-11 07:08:54.922549378    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3322, in execute_sql
2024-11-11 07:08:54.922551696      cursor.execute(sql, params or ())
2024-11-11 07:08:54.922555091  sqlite3.DatabaseError: database disk image is malformed
2024-11-11 07:08:54.922559329  
2024-11-11 07:08:54.922561530  During handling of the above exception, another exception occurred:
2024-11-11 07:08:54.922590633  
2024-11-11 07:08:54.922592875  Traceback (most recent call last):
2024-11-11 07:08:54.922595407    File "/usr/local/lib/python3.9/dist-packages/peewee_migrate/router.py", line 200, in run_one
2024-11-11 07:08:54.922597530      migrator()
2024-11-11 07:08:54.922600056    File "/usr/local/lib/python3.9/dist-packages/peewee_migrate/migrator.py", line 76, in __call__
2024-11-11 07:08:54.922628804      op.run()
2024-11-11 07:08:54.922`

**Comment by NickM-27** [comment]
Looks like your config is incorrect

**Comment by Starcon79** [comment]
> Looks like your config is incorrect

Which config, the one from frigate.yml or from the addon?

`mqtt:
  enabled: False

cameras:
  Parkplatz1: # <------ Name the camera
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://10.0.10.10:554/rtsp # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: False # <---- disable detection until you have a working camera feed`

**Comment by imatech** [comment]
Did you ever get this fixed?  I have the same issue since updating to Current version: 0.14.1.
