### ISSUE TITLE
Fontconfig error: Cannot load default config file after updating 

### ISSUE THREAD

**Issue by niemyjski** [blakeblackshear/frigate-hass-addons#5]
After updating from 1.2 to 1.3 I get the following error when the add-on starts up:

```
Fontconfig error: Cannot load default config file
On connect called
ffprobe -v panic -show_error -show_streams -of json "rtsp://x.x.xx:7447/xxxxxxxx"
Starting detection process: 35
Attempting to load TPU as usb:0
TPU found
{'error': {'code': -1094995529, 'string': 'Invalid data found when processing input'}}
Traceback (most recent call last):
  File "detect_objects.py", line 441, in <module>
    main()
  File "detect_objects.py", line 235, in main
    frame_shape = get_frame_shape(ffmpeg_input)
  File "/opt/frigate/frigate/video.py", line 40, in get_frame_shape
    video_info = [s for s in info['streams'] if s['codec_type'] == 'video'][0]
KeyError: 'streams'
```

Looking at my camera software it appears my unifi protect service was stopped (looking into it). But this error message has nothing to do with that from what I can tell. Even after the service is up. I'm still getting:

```
Fontconfig error: Cannot load default config file
On connect called
```

**Comment by blakeblackshear** [comment]
It isn't anything to worry about.
