### ISSUE TITLE
Coral USB not detected

### ISSUE THREAD

**Issue by friggeri** [blakeblackshear/frigate-hass-addons#83]
I'm running HASS OS on an Intel NUC, my USB Coral is plugged into the USB-C socket (but same issue if I use any of the USB-A ones). Using the Frigate NVR (Full Access) addon.

`lsusb` in both the HA host and the HA container show that the Coral is detected:

```
[core-ssh ~]$ lsusb
Bus 003 Device 001: ID 1d6b:0002
Bus 001 Device 001: ID 1d6b:0002
Bus 001 Device 003: ID 8087:0aaa
Bus 001 Device 002: ID 10c4:8a2a
Bus 004 Device 001: ID 1d6b:0003
Bus 002 Device 001: ID 1d6b:0003
**Bus 003 Device 002: ID 1a6e:089a**
```

```
# lsusb
Bus 003 Device 001: ID 1d6b:0002
Bus 001 Device 001: ID 1d6b:0002
Bus 001 Device 003: ID 8087:0aaa
Bus 001 Device 002: ID 10c4:8a2a
Bus 004 Device 001: ID 1d6b:0003
Bus 002 Device 001: ID 1d6b:0003
**Bus 003 Device 002: ID 1a6e:089a**
```

But when I attempt to start the Frigate addon, it crashes, here are the logs:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-10-04 08:15:42] frigate.app                    INFO    : Starting Frigate (0.11.0-3846a13)
[2022-10-04 08:15:42] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2022-10-04 08:15:42] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-10-04 08:15:42] peewee_migrate                 INFO    : There is nothing to migrate
[2022-10-04 08:15:42] detector.coral                 INFO    : Starting detection process: 224
[2022-10-04 08:15:42] frigate.app                    INFO    : Output process started: 225
[2022-10-04 08:15:42] ws4py                          INFO    : Using epoll
Process detector:coral:
[2022-10-04 08:15:42] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2022-10-04 08:15:42] frigate.app                    INFO    : Camera processor started for patio_west: 229
[2022-10-04 08:16:07] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
[2022-10-04 08:15:42] frigate.app                    INFO    : Capture process started for patio_west: 234
[2022-10-04 08:15:42] ws4py                          INFO    : Using epoll
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 135, in run_detector
    object_detector = LocalObjectDetector(
  File "/opt/frigate/frigate/edgetpu.py", line 43, in __init__
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
[2022-10-04 08:16:12] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
[2022-10-04 08:16:12] frigate.app                    INFO    : Stopping...
[2022-10-04 08:16:12] ws4py                          INFO    : Closing all websockets with [1001] 'Server is shutting down'
[2022-10-04 08:16:12] frigate.stats                  INFO    : Exiting watchdog...
[2022-10-04 08:16:12] frigate.watchdog               INFO    : Exiting watchdog...
[2022-10-04 08:16:12] frigate.events                 INFO    : Exiting event cleanup...
[2022-10-04 08:16:12] frigate.record                 INFO    : Exiting recording cleanup...
[2022-10-04 08:16:12] frigate.record                 INFO    : Exiting recording maintenance...
[2022-10-04 08:16:12] frigate.events                 INFO    : Exiting event processor...
[2022-10-04 08:16:17] frigate.object_processing      INFO    : Exiting object processor...
[2022-10-04 08:16:17] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
[2022-10-04 08:16:17] root                           INFO    : Waiting for detection process to exit gracefully...
```

For reference, here's my (very simple) configuration.

```{yaml}
mqtt:
  host: 10.0.0.152
  user: mqtt
  password: pw

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  patio_west:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pw@10.0.0.156:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - rtmp
        - path: rtsp://admin:pw@10.0.0.156:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
        - path: rtsp://admin:pw@10.0.0.156:554/live
          roles:
            - record
    detect:
      width: 1280
      height: 720
```

Would appreciate your help greatly!

**Comment by NickM-27** [comment]
Disable protected mode in the addon configuration
